Repository UMC-7-FIT-PASS/fitpass-web, pull requests merged in 2025-02, with the labels that each got.

#69 [Feature] 아이디, 비밀번호 찾기 api 연결
  src/apis/findid/findid.ts
  src/apis/findpw/findpw.ts
  src/components/PhoneVerification.tsx
  src/pages/FindId.tsx
  src/pages/FindPassword/ChangePasswordForm.tsx
  src/pages/FindPassword/FindPassword.tsx
  src/pages/FindPassword/FindPasswordForm.tsx
  src/pages/Signup/SignupStep2.tsx
Labels: 📬 API

#70 feat: 비로그인 시 로그인 유도 화면 표시되도록 변경
  src/components/setLocation/GetCurrentLocation.tsx
  src/pages/SearchLocation.tsx
Labels: ✨ Feature

#72 Feature/buy coin api
  src/apis/buyCoin.ts
  src/components/buyCoin/CoinCard.tsx
  src/components/payment/PaymentDetails.tsx
  src/components/paymentCard/PaymentCard.tsx
  src/constants/price-menu.tsx
  src/hooks/usePostPayCoin.ts
  src/index.css
  src/pages/ExploreFitness/ExploreFitness.tsx
  src/pages/Home/CardCol.tsx
  src/pages/Home/Home.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/Notice/NoticeDetail.tsx
  src/pages/Payment.tsx
  src/pages/SearchFitness.tsx
  src/types/HomeCardData.ts
  src/types/buyCoin.ts
Labels: 📬 API

#74 [Feature] 플랜 구독 api 연결
  src/apis/buyCoin.ts
  src/apis/subscibe.ts
  src/hooks/usePostPayCoin.ts
  src/hooks/usePostPlan.ts
  src/pages/Payment.tsx
  src/types/buyCoin.ts
Labels: 📬 API

#75 feat: 신규 기능 및 개선 사항 배포
  src/apis/auth.ts
  src/apis/axios-instance.ts
  src/apis/buyCoin.ts
  src/apis/findid/findid.ts
  src/apis/findpw/findpw.ts
  src/apis/subscibe.ts
  src/apis/uploadReview/axios/reviewApi.ts
  src/apis/uploadReview/quries/useReviewApi.ts
  src/apis/usepass/axios/usepassApi.ts
  src/apis/usepass/quries/useUsepassApi.ts
  src/components/Header.tsx
  src/components/PhoneVerification.tsx
  src/components/buyCoin/CoinCard.tsx
  src/components/fitnessCard/FitnessCard.tsx
  src/components/payment/PaymentDetails.tsx
  src/components/paymentCard/PaymentCard.tsx
  src/components/setLocation/GetCurrentLocation.tsx
  src/constants/price-menu.tsx
  src/context/AuthContext.tsx
  src/hooks/usePostPayCoin.ts
  src/hooks/usePostPlan.ts
  src/hooks/useSignup.ts
  src/index.css
  src/pages/ExploreFitness/ExploreFitness.tsx
  src/pages/FindId.tsx
  src/pages/FindPassword/ChangePasswordForm.tsx
  src/pages/FindPassword/FindPassword.tsx
  src/pages/FindPassword/FindPasswordForm.tsx
  src/pages/Home/CardCol.tsx
  src/pages/Home/Home.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/Notice/Notice.tsx
  src/pages/Notice/NoticeDetail.tsx
  src/pages/Payment.tsx
  src/pages/SearchFitness.tsx
  src/pages/SearchLocation.tsx
  src/pages/Signup/SignupStep2.tsx
  src/pages/UploadReview/UploadReview.tsx
  src/pages/UsePass/AvailableList.tsx
  src/pages/UsePass/CompletedList.tsx
  src/pages/UsePass/UsePass.tsx
  src/routes/Router.tsx
  src/types/HomeCardData.ts
  src/types/buyCoin.ts
  src/types/fitnessCard.ts
Labels: 📬 API, ✨ Feature

#76 [Feature] 피트니스 리뷰 보기, 패스 결제 API 연결
  src/apis/exploreFitness.ts
  src/components/fitnessCard/FitnessCard.tsx
  src/hooks/useGetFitnessList.ts
  src/hooks/useGetPaymentPass.ts
  src/hooks/useGetRecommend.ts
  src/hooks/usePostPass.ts
  src/pages/ExploreFitness/ExploreFitness.tsx
  src/pages/FitnessDetails/FitnessDetails.tsx
  src/pages/FitnessDetails/MapContainer.tsx
  src/pages/FitnessDetails/ReviewItem.tsx
  src/pages/FitnessDetails/ReviewList.tsx
  src/pages/Home/Home.tsx
  src/pages/PassPaymentSuccess.tsx
  src/pages/PurchasePass.tsx
  src/pages/UsePass/AvailableList.tsx
  src/pages/UsePass/CompletedList.tsx
  src/pages/UsePass/UsePass.tsx
  src/types/fitnessCard.ts
  src/types/review.ts
  src/utils/storageUtils.ts
Labels: 📬 API, ✨ Feature

#80 [Feature] 소셜로그인 api 연결
  package.json
  src/apis/signin/signin.ts
  src/apis/signup/social-login.ts
  src/components/AuthHandler.tsx
  src/components/socialLogin/KakaoLoginButton.tsx
  src/hooks/useSocialSignup.ts
  src/pages/Signup/SignupStep2.tsx
  src/routes/Router.tsx
  vite.config.ts
  yarn.lock
Labels: 📬 API

#84 [Feature] 어드민 페이지 레이아웃 및 라우터 구현
  index.html
  package.json
  public/svg/IcAdminDashboard.svg
  public/svg/IcAdminFitness.svg
  public/svg/IcAdminNotice.svg
  public/svg/IcAdminPay.svg
  public/svg/IcAdminSetting.svg
  public/svg/IcAdminUser.svg
  src/assets/svg/IcAdminDashboard.tsx
  src/assets/svg/IcAdminFitness.tsx
  src/assets/svg/IcAdminNotice.tsx
  src/assets/svg/IcAdminPay.tsx
  src/assets/svg/IcAdminSetting.tsx
  src/assets/svg/IcAdminUser.tsx
  src/assets/svg/index.ts
  src/components/Header.tsx
  src/components/Modal.tsx
  src/components/admin.ts
  src/components/adminCommon/AdminHeader.tsx
  src/components/adminCommon/AdminNav.tsx
  src/components/setLocation/SetLocationOption.tsx
  src/constants/admin-menu.tsx
  src/index.css
  src/layout/AdminRootLayout.tsx
  src/layout/RootLayout.tsx
  src/main.tsx
  src/pages/ExploreFitness/ExploreFitness.tsx
  src/pages/PayHistory.tsx
  src/pages/SearchFitness.tsx
  src/pages/SearchLocation.tsx
  src/pages/Signin/Signin.tsx
  src/pages/Signup/Signup.tsx
  src/pages/Signup/SignupStep2.tsx
  src/pages/admin/AdminAccount.tsx
  src/pages/admin/AdminCoin.tsx
  src/pages/admin/AdminDashboard.tsx
  src/pages/admin/AdminFitnessList.tsx
  src/pages/admin/AdminFitnessUpload.tsx
  src/pages/admin/AdminNotice.tsx
  src/pages/admin/AdminNoticeUpload.tsx
  src/pages/admin/AdminPayHistory.tsx
  src/pages/admin/AdminSettings.tsx
  src/pages/admin/AdminSubscibe.tsx
  src/pages/admin/AdminUser.tsx
  src/pages/index.ts
  src/routes/Router.tsx
  tailwind.config.js
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css

#90 fix: maps typeError 해결을 위한 수정
  src/pages/FitnessDetails/ReviewList.tsx
Labels: ✨ Feature

#96 [Feature] admin 로그인, 대시보드, 사용자 화면 ui 구현
  src/components/adminCommon/AdminHeader.tsx
  src/components/adminCommon/AdminNav.tsx
  src/pages/Signin/Signin.tsx
  src/pages/Signup/SignupStep2.tsx
  src/pages/admin/AdminDashboard.tsx
  src/pages/admin/AdminSignin.tsx
  src/pages/admin/AdminUser.tsx
  src/pages/index.ts
  src/routes/Router.tsx
Labels: ✨ Feature

#102 [feat] 어드민 대시보드, 사용자 화면 표 길이 수정
  src/pages/admin/AdminDashboard.tsx
  src/pages/admin/AdminUser.tsx
Labels: ✨ Feature, 🎨 Html&css

#101 [Feature] 피트니스 시설 등록 UI 구현
  src/assets/img/adminImgFile.png
  src/pages/FitnessDetails/FitnessDetails.tsx
  src/pages/Home/CardCol.tsx
  src/pages/Home/Home.tsx
  src/pages/admin/AdminFitnessUpload.tsx
  src/pages/admin/AdminFitnessUpload/AdminFitnessUpload.tsx
  src/pages/admin/AdminFitnessUpload/MainImgUpload.tsx
  src/pages/admin/AdminFitnessUpload/SelectCategory.tsx
  src/pages/admin/AdminFitnessUpload/SelectStatus.tsx
  src/pages/admin/AdminFitnessUpload/SetLocationModal.tsx
  src/pages/admin/AdminFitnessUpload/SubImgUpload.tsx
  src/pages/admin/AdminFitnessUpload/TimeInput.tsx
  src/pages/index.ts
Labels: ✨ Feature, 🎨 Html&css

#100 [Feature] 어드민 구매 내역 UI 구현
  src/components/SearchHeader.tsx
  src/components/adminCommon/AdminHeader.tsx
  src/components/adminCommon/SearchBar.tsx
  src/pages/Payment.tsx
  src/pages/admin/AdminPayHistory.tsx
Labels: ✨ Feature

#108 feat: 어드민 구독 상품 관리 화면 구현
  src/pages/admin/AdminSubscibe.tsx
Labels: ✨ Feature

#109 [Feature] 어드민 코인 상품 관리 UI 구현
  src/pages/admin/AdminCoin.tsx
  src/pages/admin/AdminSubscribe.tsx
  src/pages/index.ts
Labels: ✨ Feature

#117 [feat] 로그인 아이콘 크기 지정
  src/pages/Signin/InputField.tsx
  src/pages/Signin/Signin.tsx
Labels: ✨ Feature

#113 [Feat] 어드민 사용자 목록 화면 api 연결
  src/apis/config.ts
  src/hooks/useDebounce.ts
  src/pages/admin/AdminDashboard.tsx
  src/pages/admin/AdminSignin.tsx
  src/pages/admin/AdminUser.tsx
Labels: 📬 API

#114 [Feature] 어드민 구매 내역 api 연결
  src/apis/adminPayHistory/adminPayHistory.ts
  src/components/Pagination.tsx
  src/hooks/useGetAdminPayHistory.ts
  src/index.css
  src/pages/admin/AdminPayHistory.tsx
  src/types/adminPayHistory.ts
Labels: 📬 API

#107 [Feature] 피트니스 시설 목록 조회 API 연결
  src/pages/admin/AdminFitnessList/AdminFitnessList.tsx
  src/routes/Router.tsx
Labels: 📬 API

#125 [Feature] 어드민 시설 등록의 주소 검색 및 설정 모달 구현
  src/pages/admin/AdminFitnessUpload/AdminFitnessUpload.tsx
  src/pages/admin/AdminFitnessUpload/SetLocationModal.tsx
  src/routes/Router.tsx
Labels: ✨ Feature

#127 [Feature] 어드민 구독 상품 관리 API 연결
  src/apis/adminManagement/adminSubscribe.ts
  src/components/adminCommon/ManagementInput.tsx
  src/hooks/useGetAdminSubsribe.ts
  src/pages/admin/AdminSubscribe.tsx
  src/types/adminSubsribe.ts
Labels: 📬 API

#129 [Feature] 어드민 코인 상품 관리 api 연결
  src/apis/adminManagement/adminCoint.ts
  src/hooks/useGetAdminCoins.ts
  src/pages/admin/AdminCoin.tsx
  src/pages/admin/AdminSubscribe.tsx
  src/types/adminCoint.ts
Labels: 📬 API

#131 [Deploy] 어드민 시설 목록 조회, 구독 상품 및 코인 상품 관리 api 연결
  src/apis/adminManagement/adminCoint.ts
  src/apis/adminManagement/adminSubscribe.ts
  src/apis/adminNotice/axios/adminNoticeUploadApi.ts
  src/apis/adminNotice/quries/useAdminNoticeApi.ts
  src/apis/adminNotice/quries/useAdminNoticeUploadApi.ts
  src/apis/mypage/axios/authChangeApi.ts
  src/apis/mypage/quries/useAuthChangeApi.ts
  src/components/adminCommon/ManagementInput.tsx
  src/hooks/useGetAdminCoins.ts
  src/hooks/useGetAdminSubsribe.ts
  src/mocks/mockNotices.ts
  src/pages/EditProfile/ChangePhone.tsx
  src/pages/Notice/Notice.tsx
  src/pages/admin/AdminCoin.tsx
  src/pages/admin/AdminFitnessList/AdminFitnessList.tsx
  src/pages/admin/AdminFitnessUpload/AdminFitnessUpload.tsx
  src/pages/admin/AdminFitnessUpload/SetLocationModal.tsx
  src/pages/admin/AdminNotice.tsx
  src/pages/admin/AdminNoticeUpload.tsx
  src/pages/admin/AdminSubscribe.tsx
  src/routes/Router.tsx
  src/types/adminCoint.ts
  src/types/adminSubsribe.ts
Labels: 📬 API

#132 [Feature] admin 공지사항 임시저장 관련 API
  src/apis/adminNotice/axios/adminNoticeUploadApi.ts
  src/apis/adminNotice/quries/useAdminNoticeApi.ts
  src/apis/adminNotice/quries/useAdminNoticeUploadApi.ts
  src/apis/uploadReview/axios/reviewApi.ts
  src/mocks/mockNotices.ts
  src/pages/EditProfile/EditProfile.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/MyProfile.tsx
  src/pages/MyPage/ProfileModal.tsx
  src/pages/Notice/NoticeDetail.tsx
  src/pages/admin/AdminNotice.tsx
  src/pages/admin/AdminNoticeUpload.tsx
Labels: 📬 API, ✨ Feature

#139 [Feature] 어드민 피트니스 등록 API 연결
  index.html
  public/real_favicon.svg
  src/apis/postAdminFitness/axios/postAdminFitnessData.ts
  src/apis/postAdminFitness/quries/useAdminFitnessUpload.ts
  src/components/fitnessCard/FitnessCard.tsx
  src/hooks/useGetPaymentPass.ts
  src/main.tsx
  src/pages/BuyCoins.tsx
  src/pages/ExploreFitness/Dropdown.tsx
  src/pages/FitnessDetails/FitnessDetails.tsx
  src/pages/FitnessDetails/ReviewList.tsx
  src/pages/Home/Home.tsx
  src/pages/PurchasePass.tsx
  src/pages/UsePass/UsePass.tsx
  src/pages/admin/AdminFitnessList/AdminFitnessList.tsx
  src/pages/admin/AdminFitnessUpload/AdminFitnessUpload.tsx
  src/pages/admin/AdminFitnessUpload/MainImgUpload.tsx
  src/pages/admin/AdminFitnessUpload/SelectStatus.tsx
  src/pages/admin/AdminFitnessUpload/SetLocationModal.tsx
  src/pages/admin/AdminFitnessUpload/SubImgUpload.tsx
  src/pages/admin/AdminFitnessUpload/TimeInput.tsx
  src/types/kakao.d.ts
Labels: 📬 API

#142 [Feature] pc/모바일 체크 및 페이지네이션 searchParams 사용
  src/apis/adminNotice/axios/adminNoticeUploadApi.ts
  src/index.css
  src/pages/MyPage/MyCoin.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/MyProfile.tsx
  src/pages/Notice/Notice.tsx
  src/pages/UsePass/AvailableItem.tsx
  src/pages/UsePass/CompletedItem.tsx
  src/pages/UsePass/UsePass.tsx
  src/pages/admin/AdminNotice.tsx
  src/pages/admin/AdminNoticeUpload.tsx
Labels: ✨ Feature

#144 [Feature] 페이지네이션 부분 수정
  src/pages/MyPage/MyProfile.tsx
  src/pages/admin/AdminNotice.tsx
Labels: ✨ Feature

#147 [Feature] 페이지 수정
  src/hooks/useGetRecommend.ts
  src/hooks/usePostPass.ts
  src/pages/FitnessDetails/FitnessDetails.tsx
  src/pages/Home/Home.tsx
  src/pages/PassPaymentSuccess.tsx
  src/pages/admin/AdminFitnessList/AdminFitnessList.tsx
Labels: ✨ Feature

#151 [Refactor] 구독(플랜) 결제 리팩토링
  src/apis/subscribe.ts
  src/components/Header.tsx
  src/components/subscribe/PlanInfo.tsx
  src/hooks/usePostPlan.ts
  src/pages/PayHistory.tsx
  src/pages/Payment.tsx
  src/types/payment.ts
Labels: 🔨 Refactor

#153 [Refactor] 위치 설정 리팩토링 및 불필요한 코드 제거
  src/apis/adminNotice/axios/adminNoticeUploadApi.ts
  src/apis/findid/findid.ts
  src/apis/findpw/findpw.ts
  src/apis/postAdminFitness/quries/useAdminFitnessUpload.ts
  src/apis/signup/signup.ts
  src/apis/signup/social-login.ts
  src/components/Header.tsx
  src/components/setLocation/GetCurrentLocation.tsx
  src/hooks/usePostAuth.ts
  src/pages/FitnessDetails/FitnessDetails.tsx
  src/pages/FitnessDetails/ReviewList.tsx
  src/pages/LocationDetails.tsx
  src/pages/PassPaymentSuccess.tsx
  src/pages/Payment.tsx
  src/pages/UpdateReview.tsx
  src/pages/UploadReview.tsx
  src/pages/admin/AdminFitnessList/AdminFitnessList.tsx
  src/pages/admin/AdminFitnessUpload/AdminFitnessUpload.tsx
  src/pages/admin/AdminFitnessUpload/MainImgUpload.tsx
  src/pages/admin/AdminFitnessUpload/SelectCategory.tsx
  src/pages/admin/AdminFitnessUpload/SelectStatus.tsx
  src/pages/admin/AdminFitnessUpload/SetLocationModal.tsx
  src/pages/admin/AdminFitnessUpload/SubImgUpload.tsx
  src/types/kakao.d.ts
Labels: 🔨 Refactor

#156 [Deploy] 미로그인 시 UI 처리 수정
  src/pages/FitnessDetails/FitnessDetails.tsx
  src/pages/FitnessDetails/ReviewList.tsx
  src/pages/Home/Home.tsx
Labels: 🌏 Deploy
