Repository UMC-7-FIT-PASS/fitpass-web, pull requests merged in 2025-04, with the labels that each got.

#167 [Feat] 사장님 회원가입 UI 구현
  public/svg/ic_signup_owner.svg
  public/svg/ic_signup_user.svg
  src/assets/svg/IcSignupOwner.tsx
  src/assets/svg/IcSignupUser.tsx
  src/assets/svg/index.ts
  src/components/FileUploadField.tsx
  src/components/InputField.tsx
  src/components/Navbar.tsx
  src/constants/nav-menu.tsx
  src/pages/BuyCoins.tsx
  src/pages/FindId.tsx
  src/pages/FindPassword/ChangePasswordForm.tsx
  src/pages/FindPassword/FindPasswordForm.tsx
  src/pages/Home/CardCol.tsx
  src/pages/Home/Home.tsx
  src/pages/MyPage/MyProfile.tsx
  src/pages/Payment.tsx
  src/pages/Signup/Signup.tsx
  src/pages/Signup/SignupStep1.tsx
  src/pages/Signup/SignupStep2.tsx
  src/pages/index.ts
  src/pages/owner/signup/Step1.tsx
  src/pages/owner/signup/Step2.tsx
  src/pages/owner/signup/Step3.tsx
  src/routes/ownerRoutes.tsx
  src/routes/userRoutes.tsx
Labels: ✨ Feature, 🎨 Html&css

#171 [Feat] 사장님 화면 ui
  src/components/Navbar.tsx
  src/pages/Notice/Notice.tsx
  src/pages/index.ts
  src/pages/owner/dashboard/OwnerDashboard.tsx
  src/pages/owner/history/SettlementHistory.tsx
  src/pages/owner/history/UsageHistory.tsx
  src/pages/owner/notice/NoticeDetails.tsx
  src/pages/owner/notice/Notices.tsx
Labels: ✨ Feature, 🎨 Html&css

#175 [Feat] 업체 시설 관리 페이지 구현
  public/svg/Ifacilities.svg
  src/assets/svg/Ifacilities.tsx
  src/assets/svg/index.ts
  src/components/ownerFitnessCard/OwnerFitnessCard.tsx
  src/constants/nav-menu.tsx
  src/index.css
  src/mocks/Facilities.json
  src/pages/Home/Home.tsx
  src/pages/owner/facilities/FacilitiesDetails.tsx
  src/pages/owner/facilities/FacilitiesMain.tsx
  src/routes/ownerRoutes.tsx
  src/types/ownerFacilities.ts
  tsconfig.app.json
Labels: ✨ Feature

#183 feat: 사장님 대시보드 시설 없을때 처리
  src/apis/owner/dashboard.ts
  src/apis/owner/history.ts
  src/hooks/useGetOwnerDashboardQueries.ts
  src/hooks/useGetOwnerHistory.ts
  src/pages/owner/dashboard/OwnerDashboard.tsx
  src/pages/owner/history/SettlementHistory.tsx
Labels: 🎨 Html&css

#185 [Feat] 어드민 네브바 수정,
  src/apis/axios-instance.ts
  src/constants/admin-menu.tsx
  src/context/AuthContext.tsx
  src/hooks/useSignin.ts
  src/layout/RootLayout.tsx
  src/pages/admin/AdminReview.tsx
  src/pages/admin/user/AdminFitnessRequest.tsx
  src/pages/admin/user/AdminFitnessUser.tsx
  src/pages/admin/user/AdminUser.tsx
  src/pages/index.ts
  src/routes/adminRoutes.tsx
  src/routes/guard/RoleRouteGuard.tsx
Labels: ✨ Feature, 🎨 Html&css

#188 [Feat] 시설 페이지 시설 등록 UI/UX 구현
  public/svg/UploadImg.svg
  src/assets/svg/UploadImg.tsx
  src/assets/svg/index.ts
  src/components/InputField.tsx
  src/components/common/ImageUploader.tsx
  src/components/common/TimeInput.tsx
  src/components/owner/FacilitiesRegister/RegisterStep1.tsx
  src/components/owner/FacilitiesRegister/RegisterStep2.tsx
  src/components/owner/FacilitiesRegister/RegisterStep3.tsx
  src/components/owner/ownerFitnessCard/OwnerFitnessCard.tsx
  src/index.css
  src/layout/RootLayout.tsx
  src/pages/admin/AdminFitnessList/AdminFitnessList.tsx
  src/pages/admin/AdminFitnessUpload/AdminFitnessUpload.tsx
  src/pages/admin/AdminFitnessUpload/TimeInput.tsx
  src/pages/index.ts
  src/pages/owner/facilities/FacilitiesMain.tsx
  src/pages/owner/facilitiesRegister/FacilitiesRegister.tsx
  src/pages/owner/facilitiesRegister/Step1.tsx
  src/pages/owner/facilitiesRegister/Step2.tsx
  src/pages/owner/facilitiesRegister/Step3.tsx
  src/routes/ownerRoutes.tsx
  src/types/ownerFacilities.ts
Labels: ✨ Feature

#189 [Feat] 어드민 시설 회원, 승인 요청 화면 구현
  src/apis/adminUser/adminFitnessUser.ts
  src/apis/adminUser/adminOwnerFile.ts
  src/apis/adminUser/adminOwnerRequest.ts
  src/apis/adminUser/adminOwnerUser.ts
  src/apis/adminUser/adminUser.ts
  src/hooks/useGetAdminUser.ts
  src/pages/admin/user/AdminFitnessRequest.tsx
  src/pages/admin/user/AdminFitnessUser.tsx
  src/pages/admin/user/AdminUser.tsx
Labels: 📬 API, ✨ Feature

#192 [Feature] 구독 및 코인 요금제 안내 api 연동
  src/components/subscribe/PlanInfo.tsx
  src/pages/BuyCoins.tsx
  src/pages/MyPage/MyPage.tsx
  src/types/payment.ts
Labels: 📬 API

#194 [Feat] 등록된 카드 목록의 영어 상수를 한글로 매핑
  public/svg/UploadImg.svg
  src/apis/adminUser/adminFitnessUser.ts
  src/apis/adminUser/adminOwnerFile.ts
  src/apis/adminUser/adminOwnerRequest.ts
  src/apis/adminUser/adminOwnerUser.ts
  src/apis/adminUser/adminUser.ts
  src/apis/axios-instance.ts
  src/apis/mypage/axios/profileApi.ts
  src/apis/owner/dashboard.ts
  src/apis/owner/history.ts
  src/assets/svg/UploadImg.tsx
  src/assets/svg/index.ts
  src/components/InputField.tsx
  src/components/common/ImageUploader.tsx
  src/components/common/TimeInput.tsx
  src/components/owner/FacilitiesRegister/RegisterStep1.tsx
  src/components/owner/FacilitiesRegister/RegisterStep2.tsx
  src/components/owner/FacilitiesRegister/RegisterStep3.tsx
  src/components/owner/ownerFitnessCard/OwnerFitnessCard.tsx
  src/components/payment/SelectPayOption.tsx
  src/components/subscribe/PlanInfo.tsx
  src/constants/admin-menu.tsx
  src/constants/cardNames.tsx
  src/context/AuthContext.tsx
  src/hooks/useGetAdminUser.ts
  src/hooks/useGetOwnerDashboardQueries.ts
  src/hooks/useGetOwnerHistory.ts
  src/hooks/useSignin.ts
  src/index.css
  src/layout/RootLayout.tsx
  src/pages/BuyCoins.tsx
  src/pages/ExploreFitness/ExploreFitness.tsx
  src/pages/Home/Home.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/SectionComponent.tsx
  src/pages/admin/AdminFitnessList/AdminFitnessList.tsx
  src/pages/admin/AdminFitnessUpload/AdminFitnessUpload.tsx
  src/pages/admin/AdminFitnessUpload/TimeInput.tsx
  src/pages/admin/AdminReview.tsx
  src/pages/admin/user/AdminFitnessRequest.tsx
  src/pages/admin/user/AdminFitnessUser.tsx
  src/pages/admin/user/AdminUser.tsx
  src/pages/index.ts
  src/pages/owner/dashboard/OwnerDashboard.tsx
  src/pages/owner/facilities/FacilitiesMain.tsx
  src/pages/owner/facilitiesRegister/FacilitiesRegister.tsx
  src/pages/owner/facilitiesRegister/Step1.tsx
  src/pages/owner/facilitiesRegister/Step2.tsx
  src/pages/owner/facilitiesRegister/Step3.tsx
  src/pages/owner/history/SettlementHistory.tsx
  src/routes/adminRoutes.tsx
  src/routes/guard/RoleRouteGuard.tsx
  src/routes/ownerRoutes.tsx
  src/types/ownerFacilities.ts
  src/types/payment.ts
Labels: ✨ Feature

#198 [Feat] 어드민 공지사항 수정
  src/apis/adminNotice/axios/adminNoticeAPI.ts
  src/apis/adminNotice/axios/adminNoticeUploadApi.ts
  src/apis/adminNotice/quries/useAdminNoticeApi.ts
  src/apis/adminNotice/quries/useAdminNoticeUploadApi.ts
  src/pages/admin/AdminNotice.tsx
  src/pages/admin/AdminNoticeUpload.tsx
  src/routes/adminRoutes.tsx
Labels: 📬 API, ✨ Feature
