Repository UMC-7-FIT-PASS/fitpass-web, pull requests merged in 2025-05, with the labels that each got.

#204 [Fix] 등록된 카드로 코인 구매 시 발생한 오류 해결
  src/components/payment/SelectPayOption.tsx
  src/pages/Payment.tsx
Labels: 🐞 BugFix

#206 [Deploy] 등록된 카드로 코인 결제 오류 해결
  src/components/payment/SelectPayOption.tsx
  src/pages/Payment.tsx
Labels: 🌏 Deploy

#208 [Fix] 비로그인 상태에서 프로필 조회 api 연결시 오류 출력 제거
  src/apis/mypage/axios/profileApi.ts
  src/apis/mypage/quries/useProfileApi.ts
  src/apis/usepass/axios/usepassApi.ts
  src/hooks/useSignin.ts
  src/pages/MyPage/MyPage.tsx
Labels: 🔨 Refactor

#209 [Fix] 어드민 새로고침 오류 해결
  src/App.tsx
  src/components/admin.ts
  src/components/admin.tsx
  src/index.css
  src/layout/AdminRootLayout.tsx
  src/layout/RootLayout.tsx
  src/layout/RootStyleManager.tsx
Labels: 🐞 BugFix
