Repository UMC-7-FIT-PASS/fitpass-web, pull requests merged in 2025-01, with the labels that each got.

#6 헤더 및 하단바 구현
  public/svg/backIcon.svg
  public/svg/closeIcon.svg
  src/assets/svg/BackIcon.tsx
  src/assets/svg/CloseIcon.tsx
  src/assets/svg/index.ts
  src/components/Header.tsx
  src/components/Navbar.tsx
  src/constants/nav-menu.tsx
  src/pages/NotFound.tsx
Labels: ✨ Feature

#8 style: Header.tsx에 z-50 추가
  src/components/Header.tsx
Labels: 🎨 Html&css

#12 [Feature] 피트니스 시설 살펴보기 페이지 구현
  public/svg/arrow_drop_down.svg
  public/svg/arrow_drop_up.svg
  src/assets/svg/ArrowDropDown.tsx
  src/assets/svg/ArrowDropUp.tsx
  src/assets/svg/index.ts
  src/components/FitnessCard.tsx
  src/index.css
  src/pages/ExploreFitness.tsx
  src/pages/ExploreFitness/CategorySlide.tsx
  src/pages/ExploreFitness/Dropdown.tsx
  src/pages/ExploreFitness/ExploreFitness.tsx
  src/pages/Home/CardCol.tsx
  src/pages/Home/Home.tsx
  src/pages/index.ts
Labels: ✨ Feature

#25 [Feature] 코인 구매 페이지 구현
  public/svg/ArrowDown.svg
  public/svg/ArrowUp.svg
  public/svg/IcCoinWhite.svg
  public/svg/IcEmptyDollarBlue.svg
  public/svg/KakaoPay.svg
  public/svg/NaverPay.svg
  src/assets/svg/ArrowDown.tsx
  src/assets/svg/ArrowUp.tsx
  src/assets/svg/IcCoinWhite.tsx
  src/assets/svg/IcEmptyDollarBlue.tsx
  src/assets/svg/KakaoPay.tsx
  src/assets/svg/NaverPay.tsx
  src/assets/svg/index.ts
  src/components/Modal.tsx
  src/components/Navbar.tsx
  src/components/buyCoin/CoinCard.tsx
  src/components/payment/BigDropdown.tsx
  src/components/payment/PaymentDetails.tsx
  src/components/payment/PaymentInfo.tsx
  src/components/payment/SelectPayOption.tsx
  src/constants/nav-menu.tsx
  src/constants/price-menu.tsx
  src/index.css
  src/pages/BuyCoins.tsx
  src/pages/Payment.tsx
  src/routes/Router.tsx
  src/type/payment.ts
Labels: ✨ Feature

#30 [Feature] 패스 구매 및 피트니스 시설 상세 페이지 구현
  public/svg/coin_right_rounded.svg
  public/svg/pass_payment.svg
  public/svg/phonecall.svg
  public/svg/share_icon.svg
  src/assets/svg/CoinRightRounded.tsx
  src/assets/svg/PassPayment.tsx
  src/assets/svg/Phonecall.tsx
  src/assets/svg/ShareIcon.tsx
  src/assets/svg/index.ts
  src/components/Share.tsx
  src/constants/nav-menu.tsx
  src/pages/FitnessDetails.tsx
  src/pages/Home/Home.tsx
  src/pages/PassPaymentSuccess.tsx
  src/pages/PurchasePass.tsx
  src/pages/index.ts
  src/routes/Router.tsx
Labels: ✨ Feature

#33 [Feature] 아이디, 비밀번호 찾기 페이지 UI 구현
  src/pages/FindId.tsx
  src/pages/FindPassword.tsx
  src/pages/FindPassword/ChangePasswordForm.tsx
  src/pages/FindPassword/FindPassword.tsx
  src/pages/FindPassword/FindPasswordForm.tsx
  src/pages/Signin/Signin.tsx
  src/pages/Signup/SignupStep2.tsx
  src/pages/index.ts
Labels: ✨ Feature

#34 [Feature] 구독 결제 UI 구현
  public/svg/IcEmptyDollarGray.svg
  src/assets/svg/IcEmptyDollarGray.tsx
  src/assets/svg/index.ts
  src/components/Navbar.tsx
  src/components/payment/PaymentDetails.tsx
  src/components/subscribe/PlanInfo.tsx
  src/constants/nav-menu.tsx
  src/constants/price-menu.tsx
  src/pages/BuyCoins.tsx
  src/pages/Payment.tsx
  src/pages/Subscribe.tsx
  src/routes/Router.tsx
  src/type/payment.ts
  tailwind.config.js
Labels: ✨ Feature

#36 [Feature] 위치 설정 기능 구현
  index.html
  package.json
  public/fitPass-favicon.svg
  src/components/SearchHeader.tsx
  src/components/setLocation/GetCurrentLocation.tsx
  src/components/setLocation/SetLocationOption.tsx
  src/constants/nav-menu.tsx
  src/hooks/useGeoLocation.ts
  src/main.tsx
  src/pages/LocationDetails.tsx
  src/pages/SearchLocation.tsx
  src/pages/SetLocation.tsx
  src/pages/index.ts
  src/routes/Router.tsx
  tailwind.config.js
  tsconfig.json
  yarn.lock
Labels: ✨ Feature

#40 [Feature] 피트니스 상세 리뷰 페이지 구현
  public/svg/border_star.svg
  public/svg/fill_star.svg
  src/assets/svg/BorderStar.tsx
  src/assets/svg/FillStar.tsx
  src/assets/svg/index.ts
  src/components/Modal.tsx
  src/pages/FitnessDetails/FitnessDetails.tsx
  src/pages/FitnessDetails/ReviewEditDelete.tsx
  src/pages/FitnessDetails/ReviewItem.tsx
  src/pages/FitnessDetails/ReviewList.tsx
  src/pages/FitnessDetails/Share.tsx
  src/pages/index.ts
Labels: ✨ Feature

#41 [Feature] 회원가입, 로그인 API
  src/apis/config.ts
  src/apis/signin/signin.ts
  src/apis/signup/signup.ts
  src/apis/verify/verify.ts
  src/constants/nav-menu.tsx
  src/pages/Signin/InputField.tsx
  src/pages/Signin/Signin.tsx
  src/pages/Signup/Signup.tsx
  src/pages/Signup/SignupStep2.tsx
Labels: 📬 API, ✨ Feature

#47 [Feature] 시설 검색 구현
  src/pages/SearchFitness.tsx
  src/type/fitnessCard.ts
Labels: ✨ Feature

#46 [Feature] 위치 설정 api 연결
  src/apis/setLocation.ts
  src/components/setLocation/GetCurrentLocation.tsx
  src/hooks/useGeoLocation.ts
  src/hooks/usePatchLocation.ts
  src/pages/LocationDetails.tsx
  src/type/setLocation.ts
Labels: 📬 API

#55 [Feature] 구매 내역 화면 구현
  src/components/Header.tsx
  src/components/paymentCard/PaymentCard.tsx
  src/components/paymentCard/Toggle.tsx
  src/components/setLocation/SetLocationOption.tsx
  src/pages/PayHistory.tsx
  src/pages/index.ts
  src/routes/Router.tsx
Labels: ✨ Feature

#53 [Feature] 시설 검색 api 연결
  package.json
  src/apis/searchFitness.ts
  src/components/FitnessCard.tsx
  src/hooks/useGetSearchFitness.ts
  src/pages/GuideLogin.tsx
  src/pages/SearchFitness.tsx
  src/type/searchFitness.ts
  yarn.lock
Labels: 📬 API, ✨ Feature

#58 [Feature] 피트니스 찾기 API 연결
  src/assets/img/use_done.png
  src/components/Header.tsx
  src/components/fitnessCard/FitnessCard.tsx
  src/components/fitnessCard/SkeletonFitnessCard.tsx
  src/pages/ExploreFitness/CategorySlide.tsx
  src/pages/ExploreFitness/ExploreFitness.tsx
  src/pages/Home/CardCol.tsx
  src/pages/Home/Home.tsx
  src/type/HomeCardData.ts
  src/type/fitnessCard.ts
  src/utils/storageUtils.ts
Labels: 📬 API, ✨ Feature

#64 [Feat] 구매 내역 및 구독 해지 api 연결
  src/apis/payHistory.ts
  src/components/paymentCard/PaymentCard.tsx
  src/components/paymentCard/SkeletonPaymentCard.tsx
  src/hooks/useGetPayHistory.ts
  src/pages/PayHistory.tsx
  src/type/payHistory.ts
Labels: 📬 API
