Repository UMC-7-FIT-PASS/fitpass-web, pull requests merged in 2025-03, with the labels that each got.

#158 [Deploy] 헤더 수정 및 법적 정보 페이지 구현
  public/svg/hamburger.svg
  src/assets/svg/Hamburger.tsx
  src/assets/svg/index.ts
  src/components/Header.tsx
  src/components/Navbar.tsx
  src/components/header/HamburgerMenu.tsx
  src/components/header/Header.tsx
  src/components/header/MainHeader.tsx
  src/components/header/PageHeader.tsx
  src/constants/nav-menu.tsx
  src/constants/policies.ts
  src/layout/RootLayout.tsx
  src/pages/Policies/PrivacyPolicyPage.tsx
  src/pages/Policies/RefundPolicyPage.tsx
  src/pages/Policies/TermsPage.tsx
  src/pages/index.ts
  src/routes/Router.tsx
  tailwind.config.js
Labels: 🌏 Deploy

#161 위치 약관 미동의 시 모달 구현
  src/apis/signup/signup.ts
  src/context/AuthContext.tsx
  src/hooks/useSignin.ts
  src/pages/Home/Home.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/Signup/SignupStep2.tsx
Labels: 📬 API, ✨ Feature, 🎨 Html&css

#165 [Refactor] 사장님 페이지 추가 및 라우터 파일 분리
  src/pages/index.ts
  src/pages/owner/dashboard/OwnerDashboard.tsx
  src/pages/owner/facilities/FacilitiesMain.tsx
  src/pages/owner/facilitiesRegister/Step1.tsx
  src/pages/owner/facilitiesRegister/Step2.tsx
  src/pages/owner/facilitiesRegister/Step3.tsx
  src/pages/owner/history/SettlementHistory.tsx
  src/pages/owner/history/UsageHistory.tsx
  src/pages/owner/notice/NoticeDetails.tsx
  src/pages/owner/notice/Notices.tsx
  src/routes/Router.tsx
  src/routes/adminRoutes.tsx
  src/routes/ownerRoutes.tsx
  src/routes/userRoutes.tsx
Labels: 🔨 Refactor
